import { ConceptLensAction, OutputLanguage } from "./types";

export interface UiLabels {
  selected: string;
  loading: string;
  waiting: string;
  retry: string;
  save: string;
  close: string;
  stillWaitingNotice: string;
  aiDisclaimerTitle: string;
  aiDisclaimerBody: string;
  actions: Record<ConceptLensAction, string>;
  actionTitles: Record<Exclude<ConceptLensAction, "save">, string>;
  actionTooltips: Record<ConceptLensAction, string>;
}

const UI_LABELS: Record<OutputLanguage, UiLabels> = {
  bilingual: {
    selected: "选中",
    loading: "Loading...",
    waiting: "Still waiting for the AI response...",
    retry: "重试",
    save: "保存",
    close: "关闭",
    stillWaitingNotice: "The AI result is still loading.",
    aiDisclaimerTitle: "AI 生成",
    aiDisclaimerBody: "内容由 AI 生成，可能存在错误，请结合原文和多渠道交叉核对。",
    actions: {
      overview: "总览",
      explain: "解释",
      translate: "翻译",
      expand: "拓展",
      save: "保存"
    },
    actionTitles: {
      overview: "总览",
      explain: "解释",
      translate: "翻译",
      expand: "拓展"
    },
    actionTooltips: {
      overview: "Explain, translate, and expand with AI",
      explain: "Explain with AI",
      translate: "Translate with AI",
      expand: "Expand with AI",
      save: "Save as concept note"
    }
  },
  zh: {
    selected: "选中",
    loading: "加载中...",
    waiting: "仍在等待 AI 返回...",
    retry: "重试",
    save: "保存",
    close: "关闭",
    stillWaitingNotice: "AI 结果仍在加载中。",
    aiDisclaimerTitle: "AI 生成",
    aiDisclaimerBody: "内容由 AI 生成，可能存在错误，请结合原文和多渠道交叉核对。",
    actions: {
      overview: "总览",
      explain: "解释",
      translate: "翻译",
      expand: "拓展",
      save: "保存"
    },
    actionTitles: {
      overview: "总览",
      explain: "解释",
      translate: "翻译",
      expand: "拓展"
    },
    actionTooltips: {
      overview: "解释、翻译并拓展",
      explain: "AI 解释",
      translate: "AI 翻译",
      expand: "AI 拓展",
      save: "保存为概念卡"
    }
  },
  en: {
    selected: "Selected",
    loading: "Loading...",
    waiting: "Still waiting for the AI response...",
    retry: "Retry",
    save: "Save",
    close: "Close",
    stillWaitingNotice: "The AI result is still loading.",
    aiDisclaimerTitle: "AI-generated",
    aiDisclaimerBody: "This content was generated by AI and may contain mistakes. Check it against the source context and cross-check with multiple sources.",
    actions: {
      overview: "Overview",
      explain: "Explain",
      translate: "Translate",
      expand: "Expand",
      save: "Save"
    },
    actionTitles: {
      overview: "Overview",
      explain: "Explain",
      translate: "Translate",
      expand: "Expand"
    },
    actionTooltips: {
      overview: "Explain, translate, and expand with AI",
      explain: "Explain with AI",
      translate: "Translate with AI",
      expand: "Expand with AI",
      save: "Save as concept note"
    }
  },
  ko: {
    selected: "선택",
    loading: "불러오는 중...",
    waiting: "AI 응답을 기다리는 중...",
    retry: "다시",
    save: "저장",
    close: "닫기",
    stillWaitingNotice: "AI 결과를 아직 불러오는 중입니다.",
    aiDisclaimerTitle: "AI 생성",
    aiDisclaimerBody: "이 내용은 AI가 생성했으며 오류가 있을 수 있습니다. 원문 맥락과 여러 출처를 교차 확인하세요.",
    actions: {
      overview: "개요",
      explain: "설명",
      translate: "번역",
      expand: "확장",
      save: "저장"
    },
    actionTitles: {
      overview: "개요",
      explain: "설명",
      translate: "번역",
      expand: "확장"
    },
    actionTooltips: {
      overview: "AI로 설명, 번역, 확장",
      explain: "AI 설명",
      translate: "AI 번역",
      expand: "AI 확장",
      save: "개념 카드로 저장"
    }
  },
  ja: {
    selected: "選択",
    loading: "読み込み中...",
    waiting: "AI の応答を待っています...",
    retry: "再試行",
    save: "保存",
    close: "閉じる",
    stillWaitingNotice: "AI の結果をまだ読み込んでいます。",
    aiDisclaimerTitle: "AI 生成",
    aiDisclaimerBody: "この内容は AI によって生成されたもので、誤りを含む可能性があります。原文の文脈と複数の情報源で照合してください。",
    actions: {
      overview: "概要",
      explain: "説明",
      translate: "翻訳",
      expand: "発展",
      save: "保存"
    },
    actionTitles: {
      overview: "概要",
      explain: "説明",
      translate: "翻訳",
      expand: "発展"
    },
    actionTooltips: {
      overview: "AI で説明・翻訳・発展",
      explain: "AI で説明",
      translate: "AI で翻訳",
      expand: "AI で発展",
      save: "概念カードとして保存"
    }
  },
  ar: {
    selected: "المحدد",
    loading: "جار التحميل...",
    waiting: "ما زال في انتظار رد الذكاء الاصطناعي...",
    retry: "إعادة",
    save: "حفظ",
    close: "إغلاق",
    stillWaitingNotice: "ما زالت نتيجة الذكاء الاصطناعي قيد التحميل.",
    aiDisclaimerTitle: "محتوى مولد بالذكاء الاصطناعي",
    aiDisclaimerBody: "قد يحتوي هذا المحتوى المولد بالذكاء الاصطناعي على أخطاء. راجعه مع سياق النص الأصلي وتحقق منه عبر مصادر متعددة.",
    actions: {
      overview: "نظرة",
      explain: "شرح",
      translate: "ترجمة",
      expand: "توسيع",
      save: "حفظ"
    },
    actionTitles: {
      overview: "نظرة عامة",
      explain: "شرح",
      translate: "ترجمة",
      expand: "توسيع"
    },
    actionTooltips: {
      overview: "شرح وترجمة وتوسيع بالذكاء الاصطناعي",
      explain: "شرح بالذكاء الاصطناعي",
      translate: "ترجمة بالذكاء الاصطناعي",
      expand: "توسيع بالذكاء الاصطناعي",
      save: "حفظ كبطاقة مفهوم"
    }
  }
};

export function getUiLabels(language: OutputLanguage): UiLabels {
  return UI_LABELS[language] ?? UI_LABELS.bilingual;
}
